version: 1.2.1

cache: true

interface:
  customWelcome: 'Welcome to LibreChat! Enjoy your experience.'
  # Privacy policy settings
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true
  endpointsMenu: true
  modelSelect: true
  parameters: false
  sidePanel: false
  presets: false
  prompts: false
  bookmarks: false
  multiConvo: false
  agents: true
  runCode: false
mcpServers:
  paa:
    type: sse
    url: https://pr629.sell.rvtrader.com/api/sse
    timeout: 60000
    headers:
      X-User-ID: '{{LIBRECHAT_USER_ID}}'

