version: 1.2.1

cache: true

interface:
  customWelcome: "Hi, I'm Gabriel! How can I help you?"
  # Privacy policy settings
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true
  endpointsMenu: true
  modelSelect: true
  parameters: false
  sidePanel: true
  presets: false
  prompts: true
  bookmarks: false
  multiConvo: false
  agents: true
  runCode: false
mcpServers:
  paa:
    type: sse
    url: https://pr629.sell.rvtrader.com/api/sse
    timeout: 60000
    headers:
      X-User-ID: '{{LIBRECHAT_USER_ID}}'
endpoints:
  bedrock:
    titleModel: "us.anthropic.claude-3-5-haiku-20241022-v1:0"
    streamRate: 35
    availableRegions:
      - "us-east-1"
